BlogProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',views.startt,name='startt'),
    path('',include('posts.urls'))
]

posts/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
app_name='posts'

urlpatterns=[
    path("",views.startt,name='startt'),
    path("index",views.index,name = 'index'),
    path("<int:person_id>",views.Blogs,name='Blogs'),
]

posts/models.py
from django.db import models

# Create your models here.

class People (models.Model):
    Name = models.CharField(max_length=60)
    Email= models.EmailField(max_length = 254,unique = True)
    def __str__(self):
        return self.Name


class BlogContent (models.Model):
    Blogg=models.CharField(max_length=300)
    pub_date = models.DateTimeField('date Published')
    pep = models.ForeignKey(People,on_delete=models.CASCADE,related_name='Person_obj')
    def __str__(self):
        return self.Blogg
class Comments(models.Model):
    Comm= models.CharField(max_length=1000)
    pub_date = models.DateTimeField('Comment Date')
    commenter = models.CharField(max_length=60, default = 'Anonnymous')
    blg= models.ForeignKey(BlogContent,on_delete=models.CASCADE,related_name='Commentss')
    def __str__(self):
        return self.Comm

posts/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404,HttpResponseRedirect
from posts.models import People,BlogContent,Comments
from django.template import loader
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
# Create your views here.
def startt(request):
    return render(request,'startt.html')

def index(request):
    people = People.objects.order_by('Name')
    content = {'bloggers':people}
    return render(request,'index.html',content)

def Blogs(request,person_id):
    people = People.objects.get(pk=person_id)
    print(people)
    context={'pep':people}
    return render(request,'Blogs.html',context)

def Comments(request,b_id):
    #people = People.objects.get(pk=person_id)  ,p_id
    blogc=BlogContent.objects.get(pk=b_id)
    context = {'blg':blogc}
    return render(request,'Comments.html',context)

posts/templates/Blogs.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <title>Blogg of {{pep.Name}}</title>
  </head>
  <body>
    <div class="container">
      <div class="card">
    <div class="card-body">
        <h1>{{pep.Name}}</h1>
        </div>
        <div class="container">
          <h4>{{pep.Email}}</h4>
        </div>
        </div>
        </div>
          <br>
          <br>
          <div class="container">
            <ol>
              {% for bl in pep.Person_obj.all  %}
              <li>{{bl.Blogg}}</a>  -- {{bl.pub_date}} </li>
              {%endfor%}
            </ol>
          </div>
          <br>
          <br>
          <form action="{% url 'posts:index'%}" method="post">
            {% csrf_token %}
        <input class = "btn btn-warning" type="submit" value="Go Back" >
      </form>
  </body>
</html>

posts/templates/Comments.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Comments</title>
  </head>
  <body>
    <div class="container">
      <div class="card">
    <div class="card-body">
        <h1>{{blg.Blogg}}</h1>
        </div>
        <div class="container">
          <h4>{{blg.pub_date}}</h4>
        </div>
        </div>
        </div>

  </body>
</html>

posts/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Writers</title>
  </head>
  <body>
    <h1>The Writers who wrote blogs</h1>
    {% if bloggers%}
        <ul class="list-group">
          {% for bl in bloggers%}
          <li class="list-group-item"><a href="{% url 'posts:Blogs' bl.id%}">{{bl.Name}}</li>
          {% endfor %}
          </ul>
        {%else%}
        <p> No One has joined our blogg.</p>
        {% endif %}
  </body>
</html>

posts/templates/startt.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <title>New Blogg</title>
  </head>
  <body>
    <div class="navbar">
          <h1>Welcome To Blogg. :D</h1>
    </div>
<br>
    <br>
    <p>Click below to look into the Users.</p>
      <form action="{% url 'posts:index'%}" method="post">
        {% csrf_token %}
    <input class = "btn btn-warning" type="submit" value="Click Me" >
  </form>
  </body>
</html>